### ISSUE TITLE
Epic task list

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-snapshot#1]
Everything todo before it's done.

- [ ] **Frontend**
  - [ ] Build main page for selecting input criteria, including the following fields:
    - [x] Averaging parameters (**MVP**)
      - averaging time interval
      - the location
      - date range
    - [ ] Pollutants (**MVP**)
      - [ ] Link to section of resources page
      - [ ] Tooltip
    - [x] Place search (city, country, etc.) (**MVP**)
    - [ ] Inclusion of extra information sources like traffic data, nearby emissions sources, health data
    - [ ] Map display
  - [ ] Build report pages with the following components:
    - [ ] Stats (specifics TBD) (**MVP**)
    - [x] Charts (specifics TBD) (**MVP**)
       - [x] Add basic bar chart of averages data
       - [ ] Color the bars according to AQI levels (discuss)
       - [ ] Additional charts? (to be discussed)
    - [ ] Small map of sensor locations (**MVP**)
       - [x] Show markers of sensor locations
       - [ ] Show tooltip with location info when markers are clicked (to be discussed)
    - [ ] Button to share report (**MVP**)
      - [x] Permalink generation
      - [x] Copy URL to clipboard
      - [ ] Card attributes for optimal social media sharing
    - [x] Button to learn more (**MVP**)
       - [x] "Learn more" links to Resources page
       - [x] Add content for Resources page
    - [ ] Button to download report
    - [ ] Button to download data
    - [ ] Build resources page with the following components
      - [ ] Display Infographics    
      - [ ] Links to learn more about transportation emissions, health effects (**MVP**)
- [ ] Build backend to support the report generation
  - [x] Integrate API to generate report (**MVP**)
     - [x] Use Averages endpoint for main stats
     - [x] Use Locations endpoint for populating markers on the map
  - [ ] Generate and download spreadsheet of data (CSV)
- [ ] Providing documentation, that includes information about:
  - [x] Setting up the project
  - [x] Deploying the app
---
